let QUESTIONS=[],order=[],cur=0,answers=[],left=3600,tick=null;
const files=['questions-1.txt','questions-2.txt','questions-3.txt','questions-4.txt','questions-5.txt','questions-6.txt','questions-7.txt'];
async function init(){try{const parts=await Promise.all(files.map(f=>fetch(f+'?v='+Date.now()).then(r=>{if(!r.ok)throw new Error(f);return r.text()})));QUESTIONS=parseQuestions(parts.join('\n'));if(QUESTIONS.length!==100)throw new Error('عدد الأسئلة المستخرج: '+QUESTIONS.length);bankCount.textContent='100 سؤال مطابق للنص';totalHome.textContent=QUESTIONS.length;startBtn.disabled=false;startBtn.textContent='بدء الاختبار';}catch(e){bankCount.textContent='خطأ في تحميل الأسئلة';startBtn.textContent='تعذر التحميل';alert('تعذر تحميل بنك الأسئلة: '+e.message)}}
function clean(t){return t.replace(/جميع الحقوق محفوظة.*Rooted-HR\.com/gi,'').replace(/\r/g,'').replace(/\n{3,}/g,'\n\n').trim()}
function parseQuestions(txt){txt=clean(txt);let blocks=txt.split(/:\s*السؤال\s+|:السؤال\s+|:\s*(?=\d+\s*\n)/g).filter(x=>/^\s*\d+/.test(x));return blocks.map(b=>{let n=+(b.match(/^\s*(\d+)/)||[])[1];let ans=(b.match(/الإجابة:\s*(\d+)\.\s*([^\n]+)/)||[]);let a=ans[1]?+ans[1]-1:null;b=b.replace(/الإجابة:[\s\S]*$/,'').trim();let lines=b.split('\n').map(x=>x.trim()).filter(Boolean);if(/^\d+$/.test(lines[0]))lines.shift();let optStart=lines.findIndex(x=>/^1\.\s*/.test(x));let q=lines.slice(0,optStart).join(' ').trim();let opts=[];for(let i=1;i<=4;i++){let re=new RegExp('^'+i+'\\.\\s*(.*)');let idx=lines.findIndex(x=>re.test(x));let next=lines.findIndex((x,j)=>j>idx&&new RegExp('^'+(i+1)+'\\.\\s*').test(x));if(idx>=0){let slice=lines.slice(idx,next>idx?next:undefined);opts.push(slice.join(' ').replace(re,'$1').trim())}}return{n,q,o:opts,a}}).filter(q=>q.n&&q.o.length===4&&q.a!==null).sort((a,b)=>a.n-b.n)}
function sh(a){a=[...a];for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function build(){order=sh(QUESTIONS.map((_,i)=>i)).map(idx=>{let q=QUESTIONS[idx],so=sh(q.o.map((t,i)=>({t,i})));return{idx,opts:so,correct:so.findIndex(x=>x.i===q.a)}});answers=Array(order.length).fill(null)}
function start(){build();left=3600;cur=0;home.classList.add('hidden');result.classList.add('hidden');review.classList.add('hidden');exam.classList.remove('hidden');render();clearInterval(tick);tick=setInterval(()=>{left--;timerUpdate();if(left<=0)submit()},1000);timerUpdate()}
function timerUpdate(){let m=Math.floor(left/60),s=left%60;timer.textContent=String(m).padStart(2,'0')+':'+String(s).padStart(2,'0')}
function render(){let it=order[cur],qq=QUESTIONS[it.idx];qnum.textContent='السؤال '+(cur+1)+' من '+order.length+' | الأصل: '+qq.n;q.textContent=qq.q;ansbox.style.display='none';opts.innerHTML=it.opts.map((op,i)=>`<label class="opt ${answers[cur]===i?'sel':''}"><input type="radio" name="o" ${answers[cur]===i?'checked':''} onchange="choose(${i})"><span>${op.t}</span></label>`).join('');pal.innerHTML=order.map((_,i)=>`<button class="pbtn ${i===cur?'cur ':''}${answers[i]!=null?'ans':''}" onclick="go(${i})">${i+1}</button>`).join('');let n=answers.filter(x=>x!=null).length;cnt.textContent='تمت الإجابة: '+n+' / '+order.length;prog.style.width=n/order.length*100+'%'}
function choose(i){answers[cur]=i;render()}function go(i){cur=i;render()}function next(){if(cur<order.length-1){cur++;render()}}function prev(){if(cur>0){cur--;render()}}
function showAns(){let it=order[cur],txt=it.opts[it.correct].t;ansbox.innerHTML='الإجابة الصحيحة: '+txt;ansbox.style.display='block';document.querySelectorAll('.opt').forEach((e,i)=>{e.classList.remove('ok','no');if(i===it.correct)e.classList.add('ok');if(answers[cur]!==null&&i===answers[cur]&&i!==it.correct)e.classList.add('no')})}
function confirmSubmit(){let u=answers.filter(x=>x==null).length;if(confirm(u?'لديك '+u+' سؤال بدون إجابة. هل تريد التسليم؟':'هل تريد تسليم الاختبار؟'))submit()}
function submit(){clearInterval(tick);let c=0;order.forEach((it,i)=>{if(answers[i]===it.correct)c++});let pct=Math.round(c/order.length*100);exam.classList.add('hidden');result.classList.remove('hidden');score.textContent=pct+'%';scoreTxt.textContent='الإجابات الصحيحة: '+c+' من '+order.length+' — الوقت المستخدم: '+used();makeReview()}
function used(){let u=3600-left;return Math.floor(u/60)+' دقيقة و '+u%60+' ثانية'}
function makeReview(){revlist.innerHTML=order.map((it,i)=>{let qq=QUESTIONS[it.idx],u=answers[i]==null?'لم تتم الإجابة':it.opts[answers[i]].t,c=it.opts[it.correct].t,ok=answers[i]===it.correct;return `<div class="rev"><b>السؤال ${i+1} (الأصل ${qq.n}): ${qq.q}</b><p>${ok?'✅':'❌'} إجابتك: ${u}</p><p>✅ الإجابة الصحيحة: ${c}</p></div>`}).join('')}
function showReview(){review.classList.remove('hidden');review.scrollIntoView({behavior:'smooth'})}
init();